sudo: false
language: go

go:
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - tip

os:
  - linux
  - osx

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

script:
  - go build
  - go test -race -v ./...

